/**
 * This class is automatically generated by mig. DO NOT EDIT THIS FILE.
 * This class implements a Java interface to the 'UsaNetworkMsg'
 * message type.
 */

public class UsaNetworkMsg extends net.tinyos.message.Message {

    /** The default size of this message type in bytes. */
    public static final int DEFAULT_MESSAGE_SIZE = 20;

    /** The Active Message type associated with this message. */
    public static final int AM_TYPE = 5;

    /** Create a new UsaNetworkMsg of size 20. */
    public UsaNetworkMsg() {
        super(DEFAULT_MESSAGE_SIZE);
        amTypeSet(AM_TYPE);
    }

    /** Create a new UsaNetworkMsg of the given data_length. */
    public UsaNetworkMsg(int data_length) {
        super(data_length);
        amTypeSet(AM_TYPE);
    }

    /**
     * Create a new UsaNetworkMsg with the given data_length
     * and base offset.
     */
    public UsaNetworkMsg(int data_length, int base_offset) {
        super(data_length, base_offset);
        amTypeSet(AM_TYPE);
    }

    /**
     * Create a new UsaNetworkMsg using the given byte array
     * as backing store.
     */
    public UsaNetworkMsg(byte[] data) {
        super(data);
        amTypeSet(AM_TYPE);
    }

    /**
     * Create a new UsaNetworkMsg using the given byte array
     * as backing store, with the given base offset.
     */
    public UsaNetworkMsg(byte[] data, int base_offset) {
        super(data, base_offset);
        amTypeSet(AM_TYPE);
    }

    /**
     * Create a new UsaNetworkMsg using the given byte array
     * as backing store, with the given base offset and data length.
     */
    public UsaNetworkMsg(byte[] data, int base_offset, int data_length) {
        super(data, base_offset, data_length);
        amTypeSet(AM_TYPE);
    }

    /**
     * Create a new UsaNetworkMsg embedded in the given message
     * at the given base offset.
     */
    public UsaNetworkMsg(net.tinyos.message.Message msg, int base_offset) {
        super(msg, base_offset, DEFAULT_MESSAGE_SIZE);
        amTypeSet(AM_TYPE);
    }

    /**
     * Create a new UsaNetworkMsg embedded in the given message
     * at the given base offset and length.
     */
    public UsaNetworkMsg(net.tinyos.message.Message msg, int base_offset, int data_length) {
        super(msg, base_offset, data_length);
        amTypeSet(AM_TYPE);
    }

    /**
    /* Return a String representation of this message. Includes the
     * message type name and the non-indexed field values.
     */
    public String toString() {
      String s = "Message <UsaNetworkMsg> \n";
      try {
        s += "  [dummy1=0x"+Long.toHexString(get_dummy1())+"]\n";
      } catch (ArrayIndexOutOfBoundsException aioobe) { /* Skip field */ }
      try {
        s += "  [dummy2=0x"+Long.toHexString(get_dummy2())+"]\n";
      } catch (ArrayIndexOutOfBoundsException aioobe) { /* Skip field */ }
      try {
        s += "  [dummy3=0x"+Long.toHexString(get_dummy3())+"]\n";
      } catch (ArrayIndexOutOfBoundsException aioobe) { /* Skip field */ }
      try {
        s += "  [source=0x"+Long.toHexString(get_source())+"]\n";
      } catch (ArrayIndexOutOfBoundsException aioobe) { /* Skip field */ }
      try {
        s += "  [seqno=0x"+Long.toHexString(get_seqno())+"]\n";
      } catch (ArrayIndexOutOfBoundsException aioobe) { /* Skip field */ }
      try {
        s += "  [parent=0x"+Long.toHexString(get_parent())+"]\n";
      } catch (ArrayIndexOutOfBoundsException aioobe) { /* Skip field */ }
      try {
        s += "  [voltage=0x"+Long.toHexString(get_voltage())+"]\n";
      } catch (ArrayIndexOutOfBoundsException aioobe) { /* Skip field */ }
      try {
        s += "  [hopToSource=0x"+Long.toHexString(get_hopToSource())+"]\n";
      } catch (ArrayIndexOutOfBoundsException aioobe) { /* Skip field */ }
      try {
        s += "  [passNodeId=0x"+Long.toHexString(get_passNodeId())+"]\n";
      } catch (ArrayIndexOutOfBoundsException aioobe) { /* Skip field */ }
      return s;
    }

    // Message-type-specific access methods appear below.

    /////////////////////////////////////////////////////////
    // Accessor methods for field: dummy1
    //   Field type: long, unsigned
    //   Offset (bits): 0
    //   Size (bits): 32
    /////////////////////////////////////////////////////////

    /**
     * Return whether the field 'dummy1' is signed (false).
     */
    public static boolean isSigned_dummy1() {
        return false;
    }

    /**
     * Return whether the field 'dummy1' is an array (false).
     */
    public static boolean isArray_dummy1() {
        return false;
    }

    /**
     * Return the offset (in bytes) of the field 'dummy1'
     */
    public static int offset_dummy1() {
        return (0 / 8);
    }

    /**
     * Return the offset (in bits) of the field 'dummy1'
     */
    public static int offsetBits_dummy1() {
        return 0;
    }

    /**
     * Return the value (as a long) of the field 'dummy1'
     */
    public long get_dummy1() {
        return (long)getUIntBEElement(offsetBits_dummy1(), 32);
    }

    /**
     * Set the value of the field 'dummy1'
     */
    public void set_dummy1(long value) {
        setUIntBEElement(offsetBits_dummy1(), 32, value);
    }

    /**
     * Return the size, in bytes, of the field 'dummy1'
     */
    public static int size_dummy1() {
        return (32 / 8);
    }

    /**
     * Return the size, in bits, of the field 'dummy1'
     */
    public static int sizeBits_dummy1() {
        return 32;
    }

    /////////////////////////////////////////////////////////
    // Accessor methods for field: dummy2
    //   Field type: long, unsigned
    //   Offset (bits): 32
    //   Size (bits): 32
    /////////////////////////////////////////////////////////

    /**
     * Return whether the field 'dummy2' is signed (false).
     */
    public static boolean isSigned_dummy2() {
        return false;
    }

    /**
     * Return whether the field 'dummy2' is an array (false).
     */
    public static boolean isArray_dummy2() {
        return false;
    }

    /**
     * Return the offset (in bytes) of the field 'dummy2'
     */
    public static int offset_dummy2() {
        return (32 / 8);
    }

    /**
     * Return the offset (in bits) of the field 'dummy2'
     */
    public static int offsetBits_dummy2() {
        return 32;
    }

    /**
     * Return the value (as a long) of the field 'dummy2'
     */
    public long get_dummy2() {
        return (long)getUIntBEElement(offsetBits_dummy2(), 32);
    }

    /**
     * Set the value of the field 'dummy2'
     */
    public void set_dummy2(long value) {
        setUIntBEElement(offsetBits_dummy2(), 32, value);
    }

    /**
     * Return the size, in bytes, of the field 'dummy2'
     */
    public static int size_dummy2() {
        return (32 / 8);
    }

    /**
     * Return the size, in bits, of the field 'dummy2'
     */
    public static int sizeBits_dummy2() {
        return 32;
    }

    /////////////////////////////////////////////////////////
    // Accessor methods for field: dummy3
    //   Field type: int, unsigned
    //   Offset (bits): 64
    //   Size (bits): 16
    /////////////////////////////////////////////////////////

    /**
     * Return whether the field 'dummy3' is signed (false).
     */
    public static boolean isSigned_dummy3() {
        return false;
    }

    /**
     * Return whether the field 'dummy3' is an array (false).
     */
    public static boolean isArray_dummy3() {
        return false;
    }

    /**
     * Return the offset (in bytes) of the field 'dummy3'
     */
    public static int offset_dummy3() {
        return (64 / 8);
    }

    /**
     * Return the offset (in bits) of the field 'dummy3'
     */
    public static int offsetBits_dummy3() {
        return 64;
    }

    /**
     * Return the value (as a int) of the field 'dummy3'
     */
    public int get_dummy3() {
        return (int)getUIntBEElement(offsetBits_dummy3(), 16);
    }

    /**
     * Set the value of the field 'dummy3'
     */
    public void set_dummy3(int value) {
        setUIntBEElement(offsetBits_dummy3(), 16, value);
    }

    /**
     * Return the size, in bytes, of the field 'dummy3'
     */
    public static int size_dummy3() {
        return (16 / 8);
    }

    /**
     * Return the size, in bits, of the field 'dummy3'
     */
    public static int sizeBits_dummy3() {
        return 16;
    }

    /////////////////////////////////////////////////////////
    // Accessor methods for field: source
    //   Field type: int, unsigned
    //   Offset (bits): 80
    //   Size (bits): 16
    /////////////////////////////////////////////////////////

    /**
     * Return whether the field 'source' is signed (false).
     */
    public static boolean isSigned_source() {
        return false;
    }

    /**
     * Return whether the field 'source' is an array (false).
     */
    public static boolean isArray_source() {
        return false;
    }

    /**
     * Return the offset (in bytes) of the field 'source'
     */
    public static int offset_source() {
        return (80 / 8);
    }

    /**
     * Return the offset (in bits) of the field 'source'
     */
    public static int offsetBits_source() {
        return 80;
    }

    /**
     * Return the value (as a int) of the field 'source'
     */
    public int get_source() {
        return (int)getUIntBEElement(offsetBits_source(), 16);
    }

    /**
     * Set the value of the field 'source'
     */
    public void set_source(int value) {
        setUIntBEElement(offsetBits_source(), 16, value);
    }

    /**
     * Return the size, in bytes, of the field 'source'
     */
    public static int size_source() {
        return (16 / 8);
    }

    /**
     * Return the size, in bits, of the field 'source'
     */
    public static int sizeBits_source() {
        return 16;
    }

    /////////////////////////////////////////////////////////
    // Accessor methods for field: seqno
    //   Field type: int, unsigned
    //   Offset (bits): 96
    //   Size (bits): 16
    /////////////////////////////////////////////////////////

    /**
     * Return whether the field 'seqno' is signed (false).
     */
    public static boolean isSigned_seqno() {
        return false;
    }

    /**
     * Return whether the field 'seqno' is an array (false).
     */
    public static boolean isArray_seqno() {
        return false;
    }

    /**
     * Return the offset (in bytes) of the field 'seqno'
     */
    public static int offset_seqno() {
        return (96 / 8);
    }

    /**
     * Return the offset (in bits) of the field 'seqno'
     */
    public static int offsetBits_seqno() {
        return 96;
    }

    /**
     * Return the value (as a int) of the field 'seqno'
     */
    public int get_seqno() {
        return (int)getUIntBEElement(offsetBits_seqno(), 16);
    }

    /**
     * Set the value of the field 'seqno'
     */
    public void set_seqno(int value) {
        setUIntBEElement(offsetBits_seqno(), 16, value);
    }

    /**
     * Return the size, in bytes, of the field 'seqno'
     */
    public static int size_seqno() {
        return (16 / 8);
    }

    /**
     * Return the size, in bits, of the field 'seqno'
     */
    public static int sizeBits_seqno() {
        return 16;
    }

    /////////////////////////////////////////////////////////
    // Accessor methods for field: parent
    //   Field type: int, unsigned
    //   Offset (bits): 112
    //   Size (bits): 16
    /////////////////////////////////////////////////////////

    /**
     * Return whether the field 'parent' is signed (false).
     */
    public static boolean isSigned_parent() {
        return false;
    }

    /**
     * Return whether the field 'parent' is an array (false).
     */
    public static boolean isArray_parent() {
        return false;
    }

    /**
     * Return the offset (in bytes) of the field 'parent'
     */
    public static int offset_parent() {
        return (112 / 8);
    }

    /**
     * Return the offset (in bits) of the field 'parent'
     */
    public static int offsetBits_parent() {
        return 112;
    }

    /**
     * Return the value (as a int) of the field 'parent'
     */
    public int get_parent() {
        return (int)getUIntBEElement(offsetBits_parent(), 16);
    }

    /**
     * Set the value of the field 'parent'
     */
    public void set_parent(int value) {
        setUIntBEElement(offsetBits_parent(), 16, value);
    }

    /**
     * Return the size, in bytes, of the field 'parent'
     */
    public static int size_parent() {
        return (16 / 8);
    }

    /**
     * Return the size, in bits, of the field 'parent'
     */
    public static int sizeBits_parent() {
        return 16;
    }

    /////////////////////////////////////////////////////////
    // Accessor methods for field: voltage
    //   Field type: int, unsigned
    //   Offset (bits): 128
    //   Size (bits): 16
    /////////////////////////////////////////////////////////

    /**
     * Return whether the field 'voltage' is signed (false).
     */
    public static boolean isSigned_voltage() {
        return false;
    }

    /**
     * Return whether the field 'voltage' is an array (false).
     */
    public static boolean isArray_voltage() {
        return false;
    }

    /**
     * Return the offset (in bytes) of the field 'voltage'
     */
    public static int offset_voltage() {
        return (128 / 8);
    }

    /**
     * Return the offset (in bits) of the field 'voltage'
     */
    public static int offsetBits_voltage() {
        return 128;
    }

    /**
     * Return the value (as a int) of the field 'voltage'
     */
    public int get_voltage() {
        return (int)getUIntBEElement(offsetBits_voltage(), 16);
    }

    /**
     * Set the value of the field 'voltage'
     */
    public void set_voltage(int value) {
        setUIntBEElement(offsetBits_voltage(), 16, value);
    }

    /**
     * Return the size, in bytes, of the field 'voltage'
     */
    public static int size_voltage() {
        return (16 / 8);
    }

    /**
     * Return the size, in bits, of the field 'voltage'
     */
    public static int sizeBits_voltage() {
        return 16;
    }

    /////////////////////////////////////////////////////////
    // Accessor methods for field: hopToSource
    //   Field type: short, unsigned
    //   Offset (bits): 144
    //   Size (bits): 8
    /////////////////////////////////////////////////////////

    /**
     * Return whether the field 'hopToSource' is signed (false).
     */
    public static boolean isSigned_hopToSource() {
        return false;
    }

    /**
     * Return whether the field 'hopToSource' is an array (false).
     */
    public static boolean isArray_hopToSource() {
        return false;
    }

    /**
     * Return the offset (in bytes) of the field 'hopToSource'
     */
    public static int offset_hopToSource() {
        return (144 / 8);
    }

    /**
     * Return the offset (in bits) of the field 'hopToSource'
     */
    public static int offsetBits_hopToSource() {
        return 144;
    }

    /**
     * Return the value (as a short) of the field 'hopToSource'
     */
    public short get_hopToSource() {
        return (short)getUIntBEElement(offsetBits_hopToSource(), 8);
    }

    /**
     * Set the value of the field 'hopToSource'
     */
    public void set_hopToSource(short value) {
        setUIntBEElement(offsetBits_hopToSource(), 8, value);
    }

    /**
     * Return the size, in bytes, of the field 'hopToSource'
     */
    public static int size_hopToSource() {
        return (8 / 8);
    }

    /**
     * Return the size, in bits, of the field 'hopToSource'
     */
    public static int sizeBits_hopToSource() {
        return 8;
    }

    /////////////////////////////////////////////////////////
    // Accessor methods for field: passNodeId
    //   Field type: short, unsigned
    //   Offset (bits): 152
    //   Size (bits): 8
    /////////////////////////////////////////////////////////

    /**
     * Return whether the field 'passNodeId' is signed (false).
     */
    public static boolean isSigned_passNodeId() {
        return false;
    }

    /**
     * Return whether the field 'passNodeId' is an array (false).
     */
    public static boolean isArray_passNodeId() {
        return false;
    }

    /**
     * Return the offset (in bytes) of the field 'passNodeId'
     */
    public static int offset_passNodeId() {
        return (152 / 8);
    }

    /**
     * Return the offset (in bits) of the field 'passNodeId'
     */
    public static int offsetBits_passNodeId() {
        return 152;
    }

    /**
     * Return the value (as a short) of the field 'passNodeId'
     */
    public short get_passNodeId() {
        return (short)getUIntBEElement(offsetBits_passNodeId(), 8);
    }

    /**
     * Set the value of the field 'passNodeId'
     */
    public void set_passNodeId(short value) {
        setUIntBEElement(offsetBits_passNodeId(), 8, value);
    }

    /**
     * Return the size, in bytes, of the field 'passNodeId'
     */
    public static int size_passNodeId() {
        return (8 / 8);
    }

    /**
     * Return the size, in bits, of the field 'passNodeId'
     */
    public static int sizeBits_passNodeId() {
        return 8;
    }

}
